# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

# permissions:
#   contents: read

jobs:
  develop:
  

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Spring Boot Build
    - name: Spring Boot Build
      run: ./gradlew clean build --exclude-task test
    
    # Docker image Build
    - name: docker image build
      run: docker build -t yubyeongsoo/pet_119_back_develop .

     # DockeHub Login
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    # Docker Hub push
    - name: docker Hub push
      run: docker push yubyeongsoo/pet_119_back_develop
      
    # GET GitHub IP
    - name: get GitHub IP
      id: ip
      uses: haythem/public-ip@v1.2
      
    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
      
    # Add github ip to AWS
    - name: Add GitHub IP to AWS
      run : |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        
    # AWS EC2 Server Connect & Docker 명령어 실행
    - name: AWS EC2 Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }} 
        port: ${{ secrets.EC2_SSH_PORT }}
#         script_stop: true
        timeout: 60s 
#         sudo docker rm $(sudo docker stop $(sudo docker ps -a -q --filter ancestor=yubyeongsoo/pet_119_back))
#           sudo docker pull yubyeongsoo/pet_119_back
        script: |
           sudo docker stop pet_119_back_develop
           sudo docker rm pet_119_back_develop
           sudo docker rmi $(sudo docker images -q yubyeongsoo/pet_119_back_develop)
           sudo docker pull yubyeongsoo/pet_119_back_develop
           sudo docker run -d -p 7000:7000 --name pet_119_back yubyeongsoo/pet_119_back_develop
#          sudo docker rm $(sudo docker stop $(sudo docker ps -a -q --filter ancestor=yubyeongsoo/pet_119_back))
#          sudo docker run -it -d -p 8080:8080 yubyeongsoo/pet_119_back
           


        
        
          
    # REMOVE Github IP FROM security group (9)
    - name: Remove IP FROM security group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
